import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: parseInt(process.env.EMAIL_PORT || '587'),
  secure: process.env.EMAIL_PORT === '465',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

interface InquiryEmailData {
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  productTitle: string;
  quantity: number;
  notes?: string;
}

export async function sendInquiryEmail(data: InquiryEmailData) {
  const { customerName, customerPhone, customerEmail, productTitle, quantity, notes } = data;

  const mailOptions = {
    from: `"Corona Marine Inquiries" <${process.env.EMAIL_USER}>`,
    to: 'sales@coronamarineparts.com',
    subject: `New Inquiry: ${productTitle}`,
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <h2 style="color: #0E2A47;">New Product Inquiry</h2>
        <p>A new inquiry has been received for <strong>${productTitle}</strong>.</p>
        
        <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <h3 style="margin-top: 0;">Customer Details</h3>
          <p><strong>Name:</strong> ${customerName}</p>
          <p><strong>Phone:</strong> ${customerPhone}</p>
          <p><strong>Email:</strong> ${customerEmail || 'Not provided'}</p>
          <hr style="border: 0; border-top: 1px solid #ddd;" />
          <h3 style="margin-top: 15px;">Inquiry Details</h3>
          <p><strong>Product:</strong> ${productTitle}</p>
          <p><strong>Quantity:</strong> ${quantity}</p>
          <p><strong>Notes:</strong> ${notes || 'No extra notes provided.'}</p>
        </div>
        
        <p style="font-size: 12px; color: #777;">This email was automatically generated by the Corona Marine Parts website.</p>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Inquiry email sent: %s', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('Error sending inquiry email:', error);
    return { success: false, error };
  }
}
