import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

interface InquiryEmailData {
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  productTitle: string;
  quantity: number;
  notes?: string;
}

export async function sendInquiryEmail(data: InquiryEmailData) {
  const { customerName, customerPhone, customerEmail, productTitle, quantity, notes } = data;

  try {
    if (!resend) {
      console.error('Resend API key is missing. Email not sent.');
      return { success: false, error: 'API key missing' };
    }
    const { data: resendData, error } = await resend.emails.send({
      from: 'Corona Marine <onboarding@resend.dev>', // Update this after domain verification
      to: process.env.EMAIL_TO || 'sales@coronamarineparts.com',
      subject: `New Inquiry: ${productTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; text-align: left;">
          <h2 style="color: #0E2A47;">New Product Inquiry</h2>
          <p>A new inquiry has been received for <strong>${productTitle}</strong>.</p>
          
          <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Customer Details</h3>
            <p><strong>Name:</strong> ${customerName}</p>
            <p><strong>Phone:</strong> ${customerPhone}</p>
            <p><strong>Email:</strong> ${customerEmail || 'Not provided'}</p>
            <hr style="border: 0; border-top: 1px solid #ddd;" />
            <h3 style="margin-top: 15px;">Inquiry Details</h3>
            <p><strong>Product:</strong> ${productTitle}</p>
            <p><strong>Quantity:</strong> ${quantity}</p>
            <p><strong>Notes:</strong> ${notes || 'No extra notes provided.'}</p>
          </div>
          
          <p style="font-size: 12px; color: #777;">This email was automatically generated by the Corona Marine Parts website.</p>
        </div>
      `,
    });

    if (error) {
      console.error('Resend inquiry email error:', error);
      return { success: false, error };
    }

    console.log('Inquiry email sent via Resend:', resendData?.id);
    return { success: true, messageId: resendData?.id };
  } catch (error) {
    console.error('Error sending inquiry email via Resend:', error);
    return { success: false, error };
  }
}

interface ContactEmailData {
  name: string;
  email: string;
  phone?: string;
  company?: string;
  message: string;
}

export async function sendContactEmail(data: ContactEmailData) {
  const { name, email, phone, company, message } = data;

  try {
    if (!resend) {
      console.error('Resend API key is missing. Email not sent.');
      return { success: false, error: 'API key missing' };
    }
    const { data: resendData, error } = await resend.emails.send({
      from: 'Corona Marine Contact <onboarding@resend.dev>', // Update this after domain verification
      to: process.env.EMAIL_TO || 'sales@coronamarineparts.com',
      subject: `General Contact: ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; text-align: left;">
          <h2 style="color: #0E2A47;">New General Contact Inquiry</h2>
          <p>You have received a new message from the contact form.</p>
          
          <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Sender Details</h3>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Phone:</strong> ${phone || 'N/A'}</p>
            <p><strong>Company:</strong> ${company || 'N/A'}</p>
            <hr style="border: 0; border-top: 1px solid #ddd;" />
            <h3 style="margin-top: 15px;">Message</h3>
            <p style="white-space: pre-wrap;">${message}</p>
          </div>
          
          <p style="font-size: 12px; color: #777;">This email was automatically generated by the Corona Marine Parts website.</p>
        </div>
      `,
    });

    if (error) {
      console.error('Resend contact email error:', error);
      return { success: false, error };
    }

    console.log('Contact email sent via Resend:', resendData?.id);
    return { success: true, messageId: resendData?.id };
  } catch (error) {
    console.error('Error sending contact email via Resend:', error);
    return { success: false, error };
  }
}
